<div class="container" data-aos="fade-up">
      <div class="row about-container">
    <!-- Header -->
        <div class="col-lg-6 content order-lg-1 order-2">
          <h2 class="title">2D WORKS</h2>
        </div>
      </div>
    <!-- Data Filter -->
      <div class="row" data-aos="fade-up" data-aos-delay="100">
        <div class="col-lg-12 d-flex justify-content-center">
          <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">ALL</li>
            <li data-filter=".filter-app">DRAWING</li>
            <li data-filter=".filter-card">PAINTING</li>
            <li data-filter=".filter-web">SKETCHBOOK</li>
          </ul>
        </div>
      </div>
    
    
    <!-- Photo Grid -->
    <div class="row" data-aos="fade-up" data-aos-delay="200"> 
      <div class="column">
        <a href="{{site.baseurl}}/assets/site/images/art/2D/touch.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 1"><img src="{{site.baseurl}}/assets/site/images/art/2D/touch.jpg" style="width:100%" class="img-fluid"></a>
        <img src="{{site.baseurl}}/assets/site/images/art/2D/dishwash.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/character.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/omelas.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/eggshells.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/sketchbook3.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/portfolio/portfolio-3.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/hero-bg.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/sketchbooka.jpg" style="width:100%" class="img-fluid">
      </div>
      <div class="column">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/cardboard party 2.jpg" style="width:100%"class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/medusa.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/lavender.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/hands.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/oqavat.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/collage.JPG" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/evan.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/icon.JPG" style="width:100%" class="img-fluid">
      </div>  
      <div class="column">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/garment.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/neoexpression.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/chess.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/jan.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/hand studies.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/sketchbook4.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/ROMA.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/sketchbook2.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/longan.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/2D/sketchbookb.jpg" style="width:100%" class="img-fluid">
      </div>
    </div>
    </div>