<div class="container" data-aos="fade-up">
      <div class="row about-container">
    <!-- Header -->
        <div class="col-lg-6 content order-lg-1 order-2">
          <h2 class="title2">3D WORKS</h2>
        </div>
      </div>
    
    <!-- Photo Grid -->
    <div class="row" data-aos="fade-up" data-aos-delay="200"> 
      <div class="column2">
        <img src="{{site.baseurl}}/assets/site/images/art/3D/natfinal.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/3D/light.jpg" style="width:100%" class="img-fluid">
      </div>
      <div class="column2">
        <img src="{{site.baseurl}}/assets/site/images/art/3D/glorification cult.jpg" style="width:100%"class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/3D/emp.jpg" style="width:100%" class="img-fluid">
      </div>  
    </div> 
</div>
    