<div class="container" data-aos="fade-up">
       <div class="row about-container">
      <!-- Header -->
          <div class="col-lg-6 content order-lg-1 order-2">
            <h2 class="title3">DIGITAL WORKS</h2>
          </div>
        </div>
      <!-- Data Filter -->
        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
            <ul id="portfolio-flters2">
              <li data-filter="*" class="filter-active2">STILL</li>
              <li data-filter=".filter-app">VIDEO</li>
            </ul>
          </div>
        </div>
      
      
    <!-- Photo Grid -->
    <div class="row" data-aos="fade-up" data-aos-delay="200"> 
      <div class="column2">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/apples for dinner.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/glorifies.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/poster and ticket.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/poster and ticket (1).jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/pb4.jpg" style="width:100%" class="img-fluid">
      </div>
      <div class="column2">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/dream map.jpg" style="width:100%"class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/DOCUMENTATION2.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/shenchenwen-logo-1.jpg" style="width:100%" class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/ROBOTheaven.jpeg" style=width:100%s class="img-fluid">
        <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/pb.png" style="width:100%" class="img-fluid">
      </div>  
    </div> 
    <div class="column2">
      <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/pb3.jpg" style="width:100%"class="img-fluid">
      <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/pb2.jpg" style="width:100%" class="img-fluid">
      <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/pb6.jpg" style="width:100%" class="img-fluid">
      <img src="{{site.baseurl}}/assets/site/images/art/GRAPHIC/pb7.jpg" style=width:100%s class="img-fluid">
    </div>  
  </div> 