<div class="container" data-aos="fade-up">
    <div class="row about-container">

        <div class="col-lg-6 content order-lg-1 order-2">
            <h2 class="title">ABOUT ME</h2>
            <p>
                I am a first year Mechanical Engineering major at the University of Waterloo. I have a passion for arts
                and
                design, as well as a background of fine arts education. My goal as a student is to combine my artistic
                passion with the science of creation so I have the tools to build systems of the future that are not
                only
                sustainable, but beautiful.
            </p>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                <div class="icon"><i class="fa fa-wrench"></i></div>
                <h4 class="title"><a href="">Skills</a></h4>
                <ul class="description">
                    <li><b>Adobe:</b> Photoshop, Illustrator, Premiere Pro, Lightroom</li>
                    <li><b>CAD Software:</b> AutoCAD, Solidworks</li>
                    <li><b>Programming:</b> HTML, CSS, Javascript, Git, Bootstrap</li>
                </ul>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
                <div class="icon"><i class="fa fa-graduation-cap"></i></div>
                <h4 class="title"><a href="">Education</a></h4>
                <ul class="description">
                    <li><b>University of Waterloo:</b> Candidate for Bachelor of Applied Science, Honours Mechanical
                        Engineering</li>
                    <li><b>Earl Haig Secondary School:</b> Visual Arts Major, Claude Watson Art Program</li>
                    <li><b>Rhode Island School of Design:</b> Illustration Major, RISD Pre College Program</li>
                </ul>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
                <div class="icon"><i class="fa fa-paint-brush"></i></div>
                <h4 class="title"><a href="">Hobbies</a></h4>
                <p class="description">Drawing, painting, design, movies, reading, music</p>
            </div>

        </div>

        <div class="col-lg-6 background order-lg-2 order-1" data-aos="fade-left" data-aos-delay="100"></div>
    </div>

</div>