<div class="container">
      <div class="section-header">
        <h3 class="section-title">Contact</h3>
      </div>
    </div>

    <div class="container mt-5">
      <div class="row justify-content-center">

        <div class="col-lg-3 col-md-4">

          <div class="info">
            <div>
              <i class="fa fa-envelope"></i>
              <p>{{page.email}}</p>
            </div>

            <div>
              <i class="fa fa-phone"></i>
              <p>{{page.phone}}</p>
            </div>
          </div>

          <div class="social-links">
            <a href="{{page.instagram}}" class="instagram"><i class="fa fa-instagram"></i></a>
            <a href="{{page.linkedin}}" class="linkedin"><i class="fa fa-linkedin"></i></a>
          </div>

        </div>
      </div>

    </div>