<div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">

    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <a href="assets/site/images/portfolio/portfolio-1.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Merciless"><img src="assets/site/images/portfolio/portfolio-1.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>Merciless</i></h4>
            <p>Graphite drawing</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <a href="assets/site/images/portfolio/portfolio-2.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Lavender Farm"><img src="assets/site/images/portfolio/portfolio-2.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>Lavender Farm</i></h4>
            <p>Mixed media painting</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <a href="assets/site/images/portfolio/portfolio-3.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Sketchbook Excerpt"><img src="assets/site/images/portfolio/portfolio-3.jpg" class="img-fluid"
                alt=""></a>
        <div class="portfolio-info">
            <h4><i>Sketchbook Excerpt</i></h4>
            <p>Ballpoint pen drawing</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <a href="assets/site/images/portfolio/portfolio-4.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Dish Washer"><img src="assets/site/images/portfolio/portfolio-4.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>Dish Washer</i></h4>
            <p>Acrylic painting</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <a href="assets/site/images/portfolio/portfolio-5.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Touch"><img src="assets/site/images/portfolio/portfolio-5.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>Touch</i></h4>
            <p>Graphite series</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <a href="assets/site/images/portfolio/portfolio-6.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Cardboard Party"><img src="assets/site/images/portfolio/portfolio-6.jpg" class="img-fluid"
                alt=""></a>
        <div class="portfolio-info">
            <h4><i>Cardboard Party</i></h4>
            <p>Acrylic painting on cardboard</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <a href="assets/site/images/portfolio/portfolio-7.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Hand Study"><img src="assets/site/images/portfolio/portfolio-7.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>Hand Study</i></h4>
            <p>Graphite drawing</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <a href="assets/site/images/portfolio/portfolio-8.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="It Is So Cute"><img src="assets/site/images/portfolio/portfolio-8.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>It Is So Cute</i></h4>
            <p>Acrylic painting</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <a href="assets/site/images/portfolio/portfolio-9.jpg" data-gall="portfolioGallery" class="venobox preview-link"
            title="Icon"><img src="assets/site/images/portfolio/portfolio-9.jpg" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>Icon</i></h4>
            <p>Pen and marker drawing</p>
        </div>
    </div>

</div>

</div>