<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
    </div>
</footer>

<!-- Vendor JS Files -->
  <script src="{{site.baseurl}}/assets/site/vendor/jquery/jquery.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/php-email-form/validate.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/counterup/counterup.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/superfish/superfish.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/hoverIntent/hoverIntent.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/venobox/venobox.min.js"></script>
  <script src="{{site.baseurl}}/assets/site/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="{{site.baseurl}}/assets/site/js/main.js"></script>