<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<title>Joyce Chen Portfolio</title>
<meta content="" name="description">
<meta content="" name="keywords">

<!-- Favicons -->
<link href="{{site.baseurl}}/assets/site/images/favicon.png" rel="icon">
<link href="{{site.baseurl}}/assets/site/images/apple-touch-icon.png" rel="apple-touch-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700"
  rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="{{site.baseurl}}/assets/site/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="{{site.baseurl}}/assets/site/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="{{site.baseurl}}/assets/site/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<link href="{{site.baseurl}}/assets/site/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="{{site.baseurl}}/assets/site/vendor/venobox/venobox.css" rel="stylesheet">
<link href="{{site.baseurl}}/assets/site/vendor/aos/aos.css" rel="stylesheet">

<!-- Main CSS File -->
<link href="{{site.baseurl}}/assets/site/css/style.css" rel="stylesheet">