<nav id="nav-menu-container">
  <ul class="nav-menu">
    <li class="menu-active"><a href="index.html">Home</a></li>
    <li><a href="#about">About</a></li>
    <li><a href="#call-to-action">Resume</a></li>
    <li class="menu-has-children"><a href="#portfolio">Portfolio</a>
      <ul>
        <li><a href="p-art.html">Art</a>
        </li>
        <li><a href="#p-stem">STEM</a></li>
      </ul>
    </li>
    <li><a href="#contact">Contact</a>
    </li>
    <img id="mobile-nav-img" src="assets/img/logo.png" alt="Joyce Chen">
  </ul>
</nav>