
<div class="container" data-aos="fade-up">
      <div class="section-header">
        <h3 class="section-title">{{ page.art_txt.title_txt}}</h3>
        <p class="section-description">{{ page.art_txt.subtitle_txt }}<br><a
            href="{{site.baseurl}}/art/" class="cta-btn" title="Visit my full art page">{{ page.art_txt.btn_txt}} </a></p>
      </div>

<div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">

    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <a href="{{page.art_txt.one_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.one_txt.title_txt}}"><img src="{{page.art_txt.one_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.one_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.one_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <a href="{{page.art_txt.two_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.two_txt.title_txt}}"><img src="{{page.art_txt.two_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.two_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.two_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <a href="{{page.art_txt.three_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.three_txt.title_txt}}"><img src="{{page.art_txt.three_txt.img_link}}" class="img-fluid"
                alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.three_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.three_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <a href="{{page.art_txt.four_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.four_txt.title_txt}}"><img src="{{page.art_txt.four_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.four_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.four_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <a href="{{page.art_txt.five_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.five_txt.title_txt}}"><img src="{{page.art_txt.five_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.five_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.five_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <a href="{{page.art_txt.six_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.six_txt.title_txt}}"><img src="{{page.art_txt.six_txt.img_link}}" class="img-fluid"
                alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.six_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.six_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <a href="{{page.art_txt.seven_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.seven_txt.title_txt}}"><img src="{{page.art_txt.seven_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.seven_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.seven_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <a href="{{page.art_txt.eight_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.eight_txt.title_txt}}"><img src="{{page.art_txt.eight_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.eight_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.eight_txt.desc_txt}}</p>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <a href="{{page.art_txt.nine_txt.img_link}}" data-gall="portfolioGallery" class="venobox preview-link"
            title="{{page.art_txt.nine_txt.title_txt}}"><img src="{{page.art_txt.nine_txt.img_link}}" class="img-fluid" alt=""></a>
        <div class="portfolio-info">
            <h4><i>{{page.art_txt.nine_txt.title_txt}}</i></h4>
            <p>{{page.art_txt.nine_txt.desc_txt}}</p>
        </div>
    </div>

</div>
</div>