<div class="container">
    <div class="row" data-aos="zoom-in">
        <div class="col-lg-9 text-center text-lg-left">
            <h3 class="cta-title">{{ page.resume_txt.title_txt }}</h3>
        </div>
        <div class="col-lg-3 cta-btn-container text-center">
            <a class="cta-btn align-right" href="{{site.baseurl}}/assets/site/files/Joyce Chen Resume.pdf" title="View and download my resume">{{page.resume_txt.btn_txt}}</a>
        </div>
    </div>

</div>