<div class="container" data-aos="fade-up">
      <div class="section-header">
        <h3 class="section-title" id="p-stem">{{page.eng_txt.title_txt}}</h3>
        <p class="section-description">{{page.eng_txt.subtitle_txt}}</p>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-6">
          <div class="member" data-aos="fade-up" data-aos-delay="100">
            <div class="social">
              <h2><a href="{{site.baseurl}}/stem1/">{{page.eng_txt.one_txt}}</a></h2>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="member" data-aos="fade-up" data-aos-delay="200">
            <div class="social">
              <h2><a href="{{site.baseurl}}/stem2/">{{page.eng_txt.two_txt}}</a></h2>
            </div>
          </div>
        </div>
 
        <div class="col-lg-4 col-md-6">
          <div class="member" data-aos="fade-up" data-aos-delay="300">
            <div class="social">
              <h2><a href="{{site.baseurl}}/stem3/">{{page.eng_txt.three_txt}}</a></h2>
            </div>
          </div>
        </div>
      </div>

    </div>